### ISSUE TITLE
建议将界面文案内容放在资源文件内，调整返回图标大小

### ISSUE THREAD

**Issue by sues-lee** [drakeet/Seashell-app#13]
刚刚粗略体验了一下APP和源码，发现主页面的返回按钮大小比其他页面要大，文案内容放在strings文件中比较好。

**Comment by drakeet** [comment]
这个源代码已经远远落后于发行版了， 不再推荐观看。。。。已经不再开源了，我打算把这个很多问题的源代码删除掉的。。。最新的贝壳单词你可以看看：
http://fir.im/seashell

在 2015年2月14日 下午9:16，lixu <notifications@github.com>写道：

**Comment by drakeet** [comment]
诶，确实『主页面的返回按钮大小比其他页面要大』，感谢反馈！

**Comment by noprom** [comment]
最新的 贝壳单词 会开源吗？

**Comment by drakeet** [comment]
暂时不会，但很多会剥离出来写成文章。。。

**Comment by noprom** [comment]
恩，O(∩_∩)O谢谢~
